### ISSUE TITLE
POMDPs

### ISSUE THREAD

**Issue by cgc** [markkho/msdm#6]
From talking to @markkho, seems like our main aim with implementing an POMDP interface will be to have compatibility with Julia's [POMDPs.jl](https://github.com/JuliaPOMDP/POMDPs.jl) library and use a similar interface as the interface for [partially-observable stochastic games](https://github.com/markkho/msdm/blob/master/msdm/core/problemclasses/posg/posg.py). POMDPs.jl seems to provide pretty straightforward [Python support](https://github.com/JuliaPOMDP/QuickPOMDPs.jl/blob/master/examples/tiger.py).

Some differences between the POSG and POMDPs.jl interfaces that we'll have to deal with:
- the observation and reward functions have different signatures. In POMDPs.jl, the observation function is `Z(action, next_state)`, in POSG it's `Z(state, joint_action, next_state)`. In POMDPs.jl, the reward function is `R(state, action)` and in POSG it is `R(state, joint_action, next_state, observation)`. I wonder which of the two interfaces we should prefer for POMDPs? We can either depart from POSG's signature, or (with some complications) could find a scheme for POMDPs to have POSG's signature. One option could let POMDP definitions specify the version of the function that uses minimal arguments, and wrap around that in a way that is inspectable, but can be called with more arguments. Another option might be to take POSG's signature, but parse variable use sites in the function (code sample for doing this [here](https://repl.it/repls/IntentionalCurlyBinary)) when wrapping the interface for POMDPs.jl.
- The state space is supplied as a vector when constructing a POMDP in POMDPs.jl. Could be computed by taking the support of the initial state distribution.
- The action and observation spaces also need to be supplied as vectors. We could try to compute these by enumerating all states or action/next_state pairs (respectively), not unlike the way reachable states are visited in Tabular MDP construction.

It seems like the transition function and initial state distribution won't require any effort to make work.

**Comment by markkho** [comment]
Thanks @cgc !
> the observation and reward functions have different signatures. 
POSG isn't being used extensively by the library at this point, so from that perspective changing the interface won't be a problem.

> One option could let POMDP definitions specify the version of the function that uses minimal arguments, and wrap around that in a way that is inspectable, but can be called with more arguments.
I like this option (and think POSG should do the same), so if there's an easy way to do this i'm definitely for this. However I think this still creates a problem if a POMDP implementation uses, e.g., `R(s, a, s', o)` as a signature but wants to use POMDPs.jl. But I think we can convert a reward/observation function with one signature to an equivalent one in another signature by augmenting the state space (not sure how this compares to parsing the variable use sites idea you suggest).

This is rough, but here's what I have in mind: If you have an observation function with the signature `Z1: S1 x A x S1` then we can augment it to `Z2: A x S2` where `S2 = S1 x S1`. This effectively recodes the original pomdp into a new one that includes information about the previous state (in the old POMDP) in the next state (in the new POMDP). If you have a reward function defined as `R1 : S1 x A x S1 x O -> Float`, then we can define a new reward function `R3 : S3 x A -> Float` where `S3` includes information about the observation and next state. This is a little trickier than in the observation function case since the reward is going to be conditional on the action, but I think it can be made to work. We would then need to do both of these things to create a state space `S4` that combines both `S2` and `S3`. Obviously, this also causes the state space to increase substantially, which might lead to problems, esp if the state space needs to be supplied as a vector...

**Comment by cgc** [comment]
From a chat with @markkho, we're leaning towards the signatures in POMDPs.jl while including the next state as an argument for the reward function: observation function of `Z(action, next_state)` and reward function of `R(state, action, next_state)`. For compatibility with POMDPs.jl, the `R(state, action)` that it requires will be computed as an expectation of `R(state, action, next_state)` w.r.t. the transition function.

Made these calls based on typical signatures used in [Meuleau et al. 1999](https://arxiv.org/abs/1301.6720) and Kaelbling et al. 1998.

**Comment by markkho** [comment]
In a recent chat with @cgc, we discussed how to represent pomdp policies. We converged on having an interface with two parts based on action selection given an agent state* as well as next agent state updates given the previous agent state, previous action, and observation. It makes sense to have action selection explicitly return a distribution, but there was debate on whether the agent state method should return a distribution over next agent states. These are captured in these two sets of method signatures:

```
# Agent state transition as deterministic function
POMDPPolicy.action_dist(agentstate) -> Distribution[Action]
POMDPPolicy.next_agentstate(agentstate, action, observation) -> AgentState

# Agent state transition as stochastic function
POMDPPolicy.action_dist(agentstate) -> Distribution[Action]
POMDPPolicy.next_agentstate_dist(agentstate, action, observation) -> Distribution[AgentState]
```

*Another issue is whether to allow actions to be chosen based on agent state __and__ observations. This corresponds to Mealy machines (rather than Moore machines, which choose outputs/actions based on the agent state only). See [Amato, Bonet & Zilberstein (2010)](https://www.aaai.org/ocs/index.php/AAAI/AAAI10/paper/viewPaper/1865) for some discussion.

**Comment by markkho** [comment]
A first attempt at implementing POMDP interfaces here: 1a21636bc7703b8caf8d7b1471dd64e24c2c02c3
